# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coursekit < Formula
  desc "Inspect, check and tidy folders of course recordings"
  homepage "https://github.com/ElAmir-Mansour/coursekit"
  version "0.1.1"
  license "MIT"

  depends_on "ffmpeg" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ElAmir-Mansour/coursekit/releases/download/v0.1.1/coursekit_0.1.1_darwin_amd64.tar.gz"
      sha256 "4d9ed750c8c04f31065bc9931cb54f3ee00b51f2270f5f93bf815a6f8833de50"

      define_method(:install) do
        bin.install "coursekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ElAmir-Mansour/coursekit/releases/download/v0.1.1/coursekit_0.1.1_darwin_arm64.tar.gz"
      sha256 "5d5a87b5a6886f4bf3ba24dca5db1eabd0848f9b7f332170ac029ae4a43b9487"

      define_method(:install) do
        bin.install "coursekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ElAmir-Mansour/coursekit/releases/download/v0.1.1/coursekit_0.1.1_linux_amd64.tar.gz"
      sha256 "8086af4a6056aa33479c805674ae075d2426417d1ed41ba7857e10938de86a75"
      define_method(:install) do
        bin.install "coursekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ElAmir-Mansour/coursekit/releases/download/v0.1.1/coursekit_0.1.1_linux_arm64.tar.gz"
      sha256 "b3c2432238c7ffac7698f11af9d7e825e855d3230f75f6b928ebb1b20f3d2433"
      define_method(:install) do
        bin.install "coursekit"
      end
    end
  end

  test do
    assert_match "coursekit", shell_output("#{bin}/coursekit version")
  end
end
